name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ubuntu-1804_apt:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-pytest

  ubuntu-1804_apt-get:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies (ubuntu packages)
      run: sudo apt-get install python3-pytest

  ubuntu-1804_apt_update:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: install dependencies (ubuntu packages)
      run: sudo apt install python3-pytest

  ubuntu-1804_apt-get_update:
    runs-on: ubuntu-18.04
    needs: [pep8_check, pre-commit]
    steps:
    - uses: actions/checkout@v2
    - name: apt-get update
      run: sudo apt-get update
    - name: install dependencies (ubuntu packages)
      run: sudo apt-get install python3-pytest
